### PR TITLE
Math screen fixes

### LINKED ISSUE #54: [Math Game, Android] Ensure that randomized answer choices are not equal
It is possible for the Math game to generate 3 of the same answer choices for a given Math question.

### LINKED ISSUE #66: [UI, Math Game, Android] Text content is hidden by Navbar, other styling issues
image

There are a couple of style issues in this screen:
1. Answer notif text "You're so quick! Keep going" is in an awkward position and is not styled at all (needs to be bigger and centered)
2. Margins and padding of elements on the screen do not match the Figma designs. There is a lot of unused whitespace
3. Text content is hidden by Navbar.

Make sure this is tested on both Android and iOS

### LINKED ISSUE #72: Remove the cascading problems
They're too complicated, and aren't obvious that they're "cascading". It seems to frustrate the user more than amuse them.

### PR DESCRIPTION
**Pull request by Fattimo**
cascade removed. set used to keep track of all answer choices so duplicates shouldn't ever happen.

Time to get new problem changed to 5 seconds on this initial commit.

### CODE REVIEW

File: src/screens/Game/Gameplay.jsx [hunk 1]
```diff
@@ -194,7 +194,7 @@ function Gameplay({ route, navigation }) {
 
       setTimeout(() => {
         getNewProblem();
-      }, 500);
+      }, 5000);
```
Comment (shopaniuk) [inline src/screens/Game/Gameplay.jsx]: What's the reasoning for having a timeout of 5000ms? A 5s delay between questions seems way too long

File: src/screens/Game/Gameplay.jsx [hunk 2]
```diff
@@ -97,30 +97,30 @@ const pullDifficultyScore = async () => {
...
+  //     solution + Math.floor(Math.random() * 15),
+  //     solution - Math.floor(Math.random() * 15),
+  //   ];
+  //   choices.sort(() => Math.random() - 0.5);
+  //   return {
+  //     expression: a + operator + b,
+  //     solution,
+  //     choices,
+  //   };
+  // }
```
Comment (shopaniuk) [inline src/screens/Game/Gameplay.jsx]: You can just delete this

**Comment by shopaniuk** [comment]
Looks good to me, great work Matt!
